TOP_SECRET: ENC[AES256_GCM,data:1lrcYw/x,iv:Wasrkc+3CfaZuEhKbDttLTgM+madwjJFEyyJ+zu9j/4=,tag:PgyGUBL1QoMVICxNxZCEiA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZzkrUkZXd2lRUXZ5bWxv
        YWM3ZGt1S3dTSktkUXREcStLQ29XMENYOFFZClBvQjdUdUVRMTV2aTI2aWNJMHQz
        a0U5bjdKU0JuSkUxbHpFTzVjRHJibnMKLS0tIEdlUnNFdGtsT0J3dkRpTXlvQkdj
        S2hXVUpXNmlaZmJDZnMrb1h1c1FidUEKNSmBYUIofw1ee4STTS+4kbRNfsqDA9zo
        TIZs+WF8PNyAMirTZKrgLe6l9Gt3DKzK4O3xDaPwxli6DNyn8NSxbA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age18d6w7lzs06yc7zycans0dptu66vjxc7743zj5td4gkpncsvr4cesn35l76
  lastmodified: "2026-07-03T08:49:01Z"
  mac: ENC[AES256_GCM,data:HvD2gFm1Q8YJKVGylmvwo9lxCbfPiRSDsHsAvzLfGI5P5EcnolgA6yGW2Ct9svjUZ8gQ8rMlIVDPCzaJZBnMDTA42KgbhzvJRcHtW4TDaPJlTf9otDE0rPtOJW7I7nudmV1wVon2z2b27r9WoajuNnXVL/vojn9KCIQ9xkkI3nI=,iv:NOw/Guq5IpvYBRj/uco8HoDhTleewIf6m1wzC5lXRGs=,tag:qm7TRaX8O7Is7HM/JKQj3A==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.2
