[workspace]
platforms = ["linux-64"]
channels = ["https://prefix.dev/brads-forge", "conda-forge"]

[tasks]
init = "task init"

[tasks.code]
depends-on = ["init"]
cmd = "code ."

[target.unix.activation.env]
PATH = "$PWD/scripts:$PATH"

[dependencies]
deno = ">=2.9.1,<2.10"
lefthook = ">=2.1.9,<3"
xcaffold = ">=0.15.0,<0.16"
cocogitto = ">=7.0.0,<8"
task = ">=3.52.0,<4"
dprint = ">=0.55.1,<0.56"
dotnetup = ">=0.5.2,<0.6"
go-sops = ">=3.13.2,<4"
copilot-cli = ">=1.0.68,<2"
skopeo = ">=1.23.0,<2"
gh = ">=2.96.0,<3"
