on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

# NB: For this workflow to work with the built in GITHUB_TOKEN.
# You must tick "Allow GitHub Actions to create and approve pull requests".
# In the repository settings under Actions > General > Workflow permissions.
#
# Then you would also give the renovate job these permissions:
#
# ```yaml
# permissions:
#   issues: write
#   contents: write
#   pull-requests: write
# ```
#
# Assuming the above is also done, using the built in GITHUB_TOKEN is sufficient
# for Renovate to create pull requests that update anything but github actions
# themselves, if you want Renovate to update the version of the github actions
# used in this workflow files, you must create a personal access token with
# the workflow scope.
#
# see: https://github.com/renovatebot/github-action#special-token-requirements-when-using-the-github-actions-manager

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Git Checkout
        uses: actions/checkout@v6

      - name: 🤖 Run Renovate
        uses: renovatebot/github-action@v46.1.19
        env:
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_REPOSITORIES: ${{ github.repository }}

  pixi:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: ⬇️ Git Checkout
        uses: actions/checkout@v6

      - name: ✨ Setup Pixi
        uses: prefix-dev/setup-pixi@v0.10.0
        with:
          run-install: false

      - name: Update lockfiles
        run: |
          set -o pipefail
          pixi update --json | pixi exec pixi-diff-to-markdown >> diff.md

      - name: Create pull request
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: "chore(pixi): update pixi lockfile"
          title: "chore(pixi): update pixi lockfile"
          body-path: diff.md
          branch: update-pixi
          base: master
          labels: pixi
          delete-branch: true
          add-paths: pixi.lock
